
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client-agency-db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL55Dialect
      
      